Repository chirantanbanik/Wellread, pull requests merged in 2024-06, with the labels that each got.

#120 feat : Add a hover effect on features card
  src/pages/Landing.jsx
Labels: ui/ux, gssoc, level1

#135 added preloader
  package-lock.json
  package.json
  src/assets/preloader.json
  src/main.jsx
  src/pages/Preloader.jsx
Labels: working-demo

#153 Forgot password
  src/appwrite/config.js
  src/components/ForgotPassword.jsx
  src/components/Login.jsx
  src/components/ResetPassword.jsx
  src/main.jsx
Labels: enhancement, gssoc, level2

#160 Added Readme file
  .github/workflows/auto-comment-pr-merge.yml
  README.md
  src/App.css
  src/appwrite/config.js
  src/components/ForgotPassword.jsx
  src/components/Login.jsx
  src/components/ResetPassword.jsx
  src/main.jsx
  src/pages/Landing.jsx
Labels: changes-needed

#173 Search blogs
  src/pages/AllPosts.jsx
Labels: working-demo
